baseURL = "https://mikeei.github.io/"
title = "Mikeei Blog"
theme = "hugo-book"

[params]
  BookTheme = 'light'
  BookToC = false
  BookLogo = 'favicon.png'
  BookSearch = false
  BookComments = false